// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZuyB_Xtq-ET4uLv2eSPLDIn5iQ9Ta7U0',
    appId: '1:592685257700:web:b24f32e427d45a053eedf1',
    messagingSenderId: '592685257700',
    projectId: 'note-app-867de',
    authDomain: 'note-app-867de.firebaseapp.com',
    storageBucket: 'note-app-867de.appspot.com',
    measurementId: 'G-VBM79LELC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtygQ7MoaId7y1R5SJ_vYMkkaoeBKDJMI',
    appId: '1:592685257700:android:cae08f4a196e0c923eedf1',
    messagingSenderId: '592685257700',
    projectId: 'note-app-867de',
    storageBucket: 'note-app-867de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDG_fzYYsY6KiCLeU_fXpuXCc11Tada0',
    appId: '1:592685257700:ios:48e4ec0d4845e5423eedf1',
    messagingSenderId: '592685257700',
    projectId: 'note-app-867de',
    storageBucket: 'note-app-867de.appspot.com',
    androidClientId: '592685257700-ouir03jmstpv50lj52furg23qfudlruo.apps.googleusercontent.com',
    iosClientId: '592685257700-0kpu6u2u9pteefi4165546i69jofttfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDG_fzYYsY6KiCLeU_fXpuXCc11Tada0',
    appId: '1:592685257700:ios:c2fddc22292d68e53eedf1',
    messagingSenderId: '592685257700',
    projectId: 'note-app-867de',
    storageBucket: 'note-app-867de.appspot.com',
    androidClientId: '592685257700-ouir03jmstpv50lj52furg23qfudlruo.apps.googleusercontent.com',
    iosClientId: '592685257700-aibv0n21d64as86t9i3qdoo3psmrjk4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAppFirebase.RunnerTests',
  );
}
